### Hello World
GET http://localhost:3000/

### Get All
GET http://localhost:3000/configurations/v1/profiling

### Get One
GET http://localhost:3000/configurations/v1/profiling/7

### Create
//POST http://localhost:3000/configurations/v1/profiling
POST https://json-server-example-d3tb.onrender.com/configurations/v1/profiling
Content-Type: application/json

{
    "profiling": "TEST",
    "active": false,
    "companyId": 2,
    "config": { "name": "hola"}
}

### Update
//PUT http://localhost:3000/configurations/v1/profiling/7
PUT https://json-server-example-d3tb.onrender.com/configurations/v1/profiling/7
Content-Type: application/json

{    
    "profiling": "Campaña de prueba",
    "active": true,
    "companyId": 1,
    "config": {}
}

### Delete
DELETE http://localhost:3000/configurations/v1/profiling/6
